#数据源
spring:
  datasource:
    #    url: jdbc:mysql:///springboot
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/vas
  thymeleaf:
    check-template-location: false

#    mybatis
mybatis:
  config-location: #指定mybatis核心配置文件
  mapper-locations: classpath:mapper/*Mapper.xml #mapper映射文件路径
  type-aliases-package: com.skynet.vaccine.entity


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"